import java.util.Map;

/**
 * This class provides a concrete implementation of the ICellNetwork interface.
 */

public class CellNetwork implements ICellNetwork {

    // Map mapping ID to CellTower object from Processor class
    private Map<Integer, CellTower> IdToCellTower;

    // TODO field to store graph generated by CellNetwork

    // TODO map field to associate ID with vertex in graph


    /**
     * Constructor
     */
    public CellNetwork(Processor processor) {
        // TODO initialize a graph object

        // TODO add line to get map from processor object
        // IdToCellTower = processor.getCellTowerMap();


    }

    /**
     * Generates vertex in graph for each cell tower in dataset
     */
    @Override
    public void generateVertices() {

    }


    /**
     * Calculate distance between each cell tower in graph
     */
    @Override
    public void generateTowerConnections() {

    }


    /**
     * Cost function to adjust distance between two cell towers by squaring distance between towers
     * An additional penalty is applied if:
     * - cell towers owned by different providers try to connect
     * - cell towers are > 100 miles apart (no connection possible in this case)
     *
     * @return adjusted cost
     */
    @Override
    public int computePenalty() {
        return 0;
    }
}
